site:
  url: https://maplemike.github.io/technical-notes
  title: Technical Notes
  start_page: docs::index.adoc
  robots: deny
content:
  sources:
    - url: ./
      branches:
        - HEAD
        - v*
antora:
  extensions:
    - require: "@antora/lunr-extension" # https://gitlab.com/antora/antora-lunr-extension/
asciidoc:
  attributes:
    context: docs
  sourcemap: true
ui:
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/master/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true
  output_dir: _
  supplemental_files: ./supplemental-ui
urls:
  html_extension_style: indexify
  latest_version_segment_strategy: replace
  redirect_facility: static
output:
  destinations:
    - provider: fs
      clean: true
      path: build/
runtime:
  log:
    level: info
    failure_level: warn
    format: pretty
  fetch: true
  cache_dir: ./.cache/antora
